# Generated by Django 6.0 on 2026-02-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0003_ats_forms_and_email_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atsclientemailconfig',
            name='company_from_email',
            field=models.EmailField(blank=True, help_text='Correo con el que se enviarán mensajes a candidatos y, al analizar CVs con IA, comunicaciones desde tu empresa.', max_length=254, verbose_name='Correo de envío (empresa)'),
        ),
        migrations.AlterField(
            model_name='atsclientemailconfig',
            name='notification_email',
            field=models.EmailField(blank=True, help_text='Recibirás avisos de formularios, candidatos y, cuando esté activo el análisis de CVs con IA, notificaciones de resultados.', max_length=254, verbose_name='Correo de notificaciones'),
        ),
    ]
