# Generated by Django 6.0 on 2026-02-07 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0006_form_criteria_and_candidate_responses'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='atscandidatecriterionresponse',
            name='unique_candidate_criterion',
        ),
        migrations.AlterUniqueTogether(
            name='atscandidatecriterionresponse',
            unique_together={('candidate', 'criterion')},
        ),
    ]
