# Generated by Django 6.0 on 2026-02-07 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0010_atsnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='cvs_limit',
            field=models.PositiveIntegerField(default=3, verbose_name='Límite de CVs'),
        ),
    ]
