# Generated by Django 6.0 on 2026-02-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0011_alter_subscription_cvs_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='atsform',
            name='layout',
            field=models.CharField(
                choices=[('single', 'Una columna'), ('two_columns', 'Dos columnas'), ('three_columns', 'Tres columnas')],
                default='single',
                help_text='Cómo se muestran los campos en el formulario público.',
                max_length=20,
                verbose_name='Vista del formulario (grilla)',
            ),
        ),
    ]
