# Generated by Django 6.0

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0012_atsform_layout'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_plan', models.CharField(max_length=50, verbose_name='Plan anterior')),
                ('to_plan', models.CharField(max_length=50, verbose_name='Plan solicitado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('done', 'Atendida')], default='pending', max_length=20, verbose_name='Estado')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_change_requests', to='mi_app.atsclient')),
            ],
            options={
                'verbose_name': 'Solicitud de cambio de plan',
                'verbose_name_plural': 'Solicitudes de cambio de plan',
                'ordering': ['-created_at'],
            },
        ),
    ]
