# Generated by Django 6.0 on 2026-02-08 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0013_planchangerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='desired_skills',
            field=models.JSONField(blank=True, default=list, help_text='Lista de habilidades o competencias a buscar (ej. Python, Inglés B2, liderazgo).', verbose_name='Habilidades deseadas'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='profile_for_analysis',
            field=models.TextField(blank=True, help_text='Descripción del perfil buscado: requisitos, experiencia deseada, qué debe evaluar la IA en el CV.', verbose_name='Perfil para análisis con IA'),
        ),
        migrations.CreateModel(
            name='CVAnalysisConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_profile', models.TextField(blank=True, help_text='Qué perfil buscar en los CV cuando no hay vacante asociada (ej. experiencia general, habilidades clave).', verbose_name='Perfil por defecto para análisis')),
                ('default_desired_skills', models.JSONField(blank=True, default=list, help_text='Lista de habilidades a evaluar cuando no hay vacante (ej. Comunicación, Excel).', verbose_name='Habilidades deseadas por defecto')),
                ('analysis_instructions', models.TextField(blank=True, help_text='Criterios extra o cómo debe interpretar la IA el CV (opcional).', verbose_name='Instrucciones adicionales para la IA')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cv_analysis_config', to='mi_app.atsclient')),
            ],
            options={
                'verbose_name': 'Configuración análisis CV',
                'verbose_name_plural': 'Configuraciones análisis CV',
            },
        ),
    ]
