# Generated by Django 6.0 on 2026-03-01 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0016_atsclient_langsmith_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atsclient',
            options={'verbose_name': 'Cliente Órbita', 'verbose_name_plural': 'Clientes Órbita'},
        ),
        migrations.AlterModelOptions(
            name='atsclientemailconfig',
            options={'verbose_name': 'Configuración de correo Órbita', 'verbose_name_plural': 'Configuraciones de correo Órbita'},
        ),
        migrations.AlterModelOptions(
            name='atsform',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Formulario Órbita', 'verbose_name_plural': 'Formularios Órbita'},
        ),
        migrations.AlterModelOptions(
            name='atsnotification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notificación Órbita', 'verbose_name_plural': 'Notificaciones Órbita'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'Suscripción Órbita', 'verbose_name_plural': 'Suscripciones Órbita'},
        ),
        migrations.CreateModel(
            name='FormChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_uuid', models.UUIDField(editable=False, unique=True, verbose_name='UUID de sesión')),
                ('status', models.CharField(choices=[('started', 'Iniciada'), ('in_progress', 'En progreso'), ('completed', 'Completada')], default='started', max_length=20, verbose_name='Estado')),
                ('current_step', models.PositiveSmallIntegerField(default=0, verbose_name='Paso actual')),
                ('total_steps', models.PositiveSmallIntegerField(default=0, verbose_name='Total de pasos')),
                ('answers', models.JSONField(default=dict, verbose_name='Respuestas parciales')),
                ('candidate_name', models.CharField(blank=True, max_length=200, verbose_name='Nombre del candidato')),
                ('candidate_email', models.EmailField(blank=True, max_length=254, verbose_name='Email del candidato')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Inicio')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actividad')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completada')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='mi_app.atsform')),
                ('submission', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_session', to='mi_app.atsformsubmission')),
            ],
            options={
                'verbose_name': 'Sesión de chat',
                'verbose_name_plural': 'Sesiones de chat',
                'ordering': ['-updated_at'],
            },
        ),
    ]
