# Generated by Django 6.0 on 2026-03-02 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0018_vacancy_ai_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='formchatsession',
            name='source',
            field=models.CharField(choices=[('web', 'Web'), ('telegram', 'Telegram')], default='web', max_length=20, verbose_name='Origen'),
        ),
        migrations.AlterField(
            model_name='atsnotification',
            name='type',
            field=models.CharField(choices=[('submission', 'Nuevo envío'), ('candidate', 'Nuevo candidato'), ('plan', 'Plan actualizado'), ('cvs_limit', 'Límite de CVs'), ('admin', 'Mensaje del administrador')], default='submission', max_length=30, verbose_name='Tipo'),
        ),
    ]
