# Generated by Django 6.0 on 2026-03-30 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0019_formchatsession_source_alter_atsnotification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='atsclientemailconfig',
            name='incoming_subject_regex',
            field=models.CharField(blank=True, help_text='Opcional. Solo se tomarán en cuenta correos entrantes cuyo asunto cumpla esta expresión regular. Ejemplo: (?i)(postulante|interesado en la vacante).', max_length=255, verbose_name='Filtro de asunto (regex)'),
        ),
    ]
