# Generated by Django 6.0 on 2026-03-30 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0020_atsclientemailconfig_incoming_subject_regex'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvanalysisconfig',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Si se desactiva, se bloquea el análisis de CV con IA para este cliente.', verbose_name='Habilitar análisis con IA'),
        ),
    ]
