# Generated by Django 6.0 on 2026-03-30 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0021_cvanalysisconfig_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='atsclientemailconfig',
            name='imap_enabled',
            field=models.BooleanField(default=False, help_text='Activa la lectura de correos entrantes para crear postulaciones automáticamente.', verbose_name='Procesar correos entrantes (IMAP)'),
        ),
        migrations.AddField(
            model_name='atsclientemailconfig',
            name='imap_folder',
            field=models.CharField(blank=True, default='INBOX', max_length=120, verbose_name='Carpeta IMAP'),
        ),
        migrations.AddField(
            model_name='atsclientemailconfig',
            name='imap_host',
            field=models.CharField(blank=True, max_length=255, verbose_name='Servidor IMAP'),
        ),
        migrations.AddField(
            model_name='atsclientemailconfig',
            name='imap_password_encrypted',
            field=models.CharField(blank=True, max_length=255, verbose_name='Contraseña IMAP (encriptada)'),
        ),
        migrations.AddField(
            model_name='atsclientemailconfig',
            name='imap_port',
            field=models.PositiveIntegerField(blank=True, default=993, null=True, verbose_name='Puerto IMAP'),
        ),
        migrations.AddField(
            model_name='atsclientemailconfig',
            name='imap_use_ssl',
            field=models.BooleanField(default=True, verbose_name='Usar SSL en IMAP'),
        ),
        migrations.AddField(
            model_name='atsclientemailconfig',
            name='imap_user',
            field=models.CharField(blank=True, max_length=255, verbose_name='Usuario IMAP'),
        ),
    ]
