# Generated by Django 6.0 on 2026-03-30 20:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0022_atsclientemailconfig_imap_enabled_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atsformcriterion',
            options={'ordering': ['-score_value', 'order', 'id'], 'verbose_name': 'Criterio de evaluación', 'verbose_name_plural': 'Criterios de evaluación'},
        ),
        migrations.AddField(
            model_name='atsformcriterion',
            name='score_value',
            field=models.PositiveSmallIntegerField(default=100, help_text='Peso de este criterio en la evaluación manual. 0 lo ignora; 100 máximo peso.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Valor (0-100)'),
        ),
        migrations.AddField(
            model_name='atsformcriterion',
            name='source_form_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_criteria', to='mi_app.atsformfield', verbose_name='Campo origen del formulario'),
        ),
        migrations.AddField(
            model_name='atsformfield',
            name='option_values',
            field=models.JSONField(blank=True, default=list, help_text='Para tipo radio o selección múltiple. Lista de opciones visibles para el candidato.', verbose_name='Opciones'),
        ),
        migrations.AlterField(
            model_name='atsformfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Texto corto'), ('email', 'Correo electrónico'), ('phone', 'Teléfono'), ('textarea', 'Texto largo (párrafo)'), ('radio', 'Opción única (radio)'), ('multi_select', 'Selección múltiple'), ('file', 'Archivo (CV/PDF)')], default='text', max_length=20, verbose_name='Tipo'),
        ),
    ]
