# Generated by Django 6.0 on 2026-03-30 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0023_alter_atsformcriterion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formchatsession',
            name='telegram_user_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='ID de usuario en Telegram'),
        ),
        migrations.AddIndex(
            model_name='formchatsession',
            index=models.Index(fields=['form', 'source', 'telegram_user_id'], name='chat_form_src_tg_idx'),
        ),
    ]
