# Generated by Django 6.0 on 2026-05-13 15:58

import mi_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0024_formchatsession_telegram_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atsclient',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=mi_app.models.ats_client_avatar_upload_to, verbose_name='Foto de perfil'),
        ),
        migrations.AlterField(
            model_name='atsformsubmissionfile',
            name='file',
            field=models.FileField(upload_to=mi_app.models.submission_file_upload_to, verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to=mi_app.models.candidate_cv_upload_to, verbose_name='Archivo CV'),
        ),
    ]
