# Generated by Django 6.0 on 2026-05-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0025_alter_atsclient_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='module_account',
            field=models.BooleanField(default=True, verbose_name='Módulo mi cuenta'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='module_candidates',
            field=models.BooleanField(default=True, verbose_name='Módulo candidatos'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='module_cv_analysis',
            field=models.BooleanField(default=True, verbose_name='Módulo config. análisis CV'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='module_email_config',
            field=models.BooleanField(default=True, verbose_name='Módulo config. correo'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='module_forms',
            field=models.BooleanField(default=True, verbose_name='Módulo formularios'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='module_notifications',
            field=models.BooleanField(default=True, verbose_name='Módulo notificaciones'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='module_vacancies',
            field=models.BooleanField(default=True, verbose_name='Módulo vacantes'),
        ),
    ]
