# Generated by Django 6.0 on 2026-05-18 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def populate_workforce_stages(apps, schema_editor):
    WorkforcePlan = apps.get_model('mi_app', 'WorkforcePlan')
    WorkforcePlan.objects.filter(status='pendiente').update(approval_stage='rh')
    WorkforcePlan.objects.filter(status__in=['aprobado', 'convertido_vacante']).update(approval_stage='vacante')
    WorkforcePlan.objects.filter(status='rechazado').update(approval_stage='rh')


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0030_workforce_public_ids'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='atsclient',
            name='workforce_role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('rh', 'RH'), ('direccion', 'Dirección'), ('finanzas', 'Finanzas'), ('reclutador', 'Reclutador')], default='admin', max_length=30, verbose_name='Rol Workforce'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='area_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Área'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='estimated_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Presupuesto estimado'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='status',
            field=models.CharField(choices=[('abierta', 'Abierta'), ('pausada', 'Pausada'), ('cerrada', 'Cerrada')], default='abierta', max_length=30, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='workforceplan',
            name='approval_stage',
            field=models.CharField(choices=[('solicitud', 'Solicitud'), ('rh', 'RH'), ('direccion', 'Dirección'), ('finanzas', 'Finanzas'), ('vacante', 'Vacante')], default='solicitud', max_length=30, verbose_name='Etapa de aprobación'),
        ),
        migrations.AlterField(
            model_name='workforceplan',
            name='status',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('pendiente', 'Pendiente de aprobación'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('convertido_vacante', 'Convertido en vacante'), ('cancelado', 'Cancelado')], default='borrador', max_length=50, verbose_name='Estado'),
        ),
        migrations.RunPython(populate_workforce_stages, migrations.RunPython.noop),
        migrations.CreateModel(
            name='WorkforceAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80, verbose_name='Acción')),
                ('previous_status', models.CharField(blank=True, max_length=50, verbose_name='Estado anterior')),
                ('new_status', models.CharField(blank=True, max_length=50, verbose_name='Estado nuevo')),
                ('comment', models.TextField(blank=True, verbose_name='Comentario')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workforce_audit_logs', to='mi_app.atsclient')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='mi_app.workforceplan')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auditoría Workforce',
                'verbose_name_plural': 'Auditoría Workforce',
                'ordering': ['-created_at'],
            },
        ),
    ]
