# Generated by Django 6.0 on 2026-05-21 02:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0031_atsclient_workforce_role_vacancy_area_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacancyDashboardConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier1_min', models.PositiveSmallIntegerField(default=72, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Mínimo Tier 1')),
                ('tier2_min', models.PositiveSmallIntegerField(default=60, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Mínimo Tier 2')),
                ('tier3_min', models.PositiveSmallIntegerField(default=40, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Mínimo Tier 3')),
                ('skill_pass_min', models.PositiveSmallIntegerField(default=70, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Habilidad aprobada desde')),
                ('skill_warning_min', models.PositiveSmallIntegerField(default=40, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Habilidad en revisión desde')),
                ('max_criteria', models.PositiveSmallIntegerField(default=8, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(12)], verbose_name='Criterios máximos')),
                ('show_kpis', models.BooleanField(default=True, verbose_name='Mostrar KPIs')),
                ('show_ranking', models.BooleanField(default=True, verbose_name='Mostrar ranking')),
                ('show_radar', models.BooleanField(default=True, verbose_name='Mostrar radar de criterios')),
                ('show_gaps', models.BooleanField(default=True, verbose_name='Mostrar gaps críticos')),
                ('show_score_bands', models.BooleanField(default=True, verbose_name='Mostrar bandas de score')),
                ('show_scatter', models.BooleanField(default=True, verbose_name='Mostrar match IA vs score')),
                ('show_ai_insights', models.BooleanField(default=True, verbose_name='Mostrar lectura IA')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vacancy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_config', to='mi_app.vacancy')),
            ],
            options={
                'verbose_name': 'Configuración dashboard de vacante',
                'verbose_name_plural': 'Configuraciones dashboard de vacante',
            },
        ),
    ]
